### ISSUE TITLE
Automatically remove the depricated Redirect URL field

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#17]
The Redirect URL field is flagged as deprecated and instead there is a new field for javascript or plaintext redirects. Because the new plaintext version works the same as the now deprecated field, there is no reason to keep it. Man in the Middle should automatically edit all relevant rules and move the content from the old field to the new one and abolishing the old field completely.

**Comment by dangkyokhoang** [comment]
Since there's no built-in way to verify that `browser.storage.sync` is up-to-date, making changes to local data might rewrite the newer data version, if there is, with the old one and hence data lost.  
![Web extension data syncing problem - Man in the Middle](https://user-images.githubusercontent.com/14311741/54966763-eadd1180-4fa7-11e9-801a-16ec6bc5845a.png)

I encountered this problem when upgrading the extension from v2 to v3, where `match pattern`s were automatically replaced with `URL filter`s.

---
One method I could think of is storing metadata externally but it affects user privacy. Any suggestion will be appreciated!

**Comment by t2YU2m8l83** [comment]
To be honest, I have no clue how plugins store their data. I could think of the browser sql files or config files inside the profiles folder. Either way the privacy level is the same and I can't imagine that plugin data is stored encrypted. Therefore you could use a simple json file to store everything on start/close of Firefox and simply update this file on plugin restart. If you add a version field to the json, you can easily convert it to the next version.

**Comment by dangkyokhoang** [comment]
Extension storage is something like that. The problem is that I can't upload the JSON somewhere and fetch it on browser start. Data syncing is done by the browser and extensions can only listen to changes.

A version field is what I used in the previous upgrade. However it only tells whether the data needs upgrading/conversion but doesn't tell whether the data is up-to-date/the newest.

P/s: I actually can upload the JSON and fetch it. Then the issue can definitely be solved. However, as stated before, it affects user privacy so I just won't do that.
