### ISSUE TITLE
Response manipulation help and potential bug

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#18]
The following website updates it's content through a json file. Inside the json file is an attribute called "nsfw". I want to edit the response content of those json files to set nsfw to 0. Sadly I couldn't get it to work. The response rules are only applying on initial page load and not on javscript triggered responses.

Website:
https://9gag.com/darkhumor

Example json request url:
https://9gag.com/v1/group-posts/group/darkhumor/type/hot?after=adL2P7Z%2CaE2XqoG%2CabY2v2E&c=20

Example Code:
```
if(responseHeaders.get('Content-Type') == 'application/json'){
responseBody = responseBody.replace('"nsfw":1', '"nsfw":0');
}
return responseBody;
```

**Comment by dangkyokhoang** [comment]
1. Header methods only apply to **Header Rules**:
  ![Man in the Middle - Modify request reponse](https://user-images.githubusercontent.com/14311741/55472817-3d1cd300-5637-11e9-898e-c6c210206fda.png)
  Therefore, `responseHeaders.get` will throw an error.
2. You don't need to verify that `Content-Type` is `application/json`. The string `"nsfw":1` already tell that it comes from a json object _(on this site, at least)_.
  - If you want to replace only xhr requests, set `URL filters` to `/^https:\/\/9gag\.com\/.*\/type\/hot/`.
  - If you otherwise want to replace pages and xhr requests, which is likely to be the case, `/^https:\/\/9gag\.com/` is enough. (Note that **Response Rules are expensive**, don't forget to make use of `URL filters` as much as possible.)
3. `responseBody.replace('"nsfw":1', '"nsfw":0');` only replaces the first occurrence, if there is. To replace all occurrences, use `/"nsfw":1/g`.
---
With all that said, the rule should be as follow:
- Text response: `return responseBody.replace(/"nsfw":1/g, '"nsfw":0');`
- Text type: `JavaScript`
- URL filters: `/^https:\/\/9gag\.com/`

**Comment by t2YU2m8l83** [comment]
Your example works perfect. Thank you.
