### ISSUE TITLE
Set-Cookie response header cannot be modified in Chrome

### ISSUE THREAD

**Issue by dinh** [dangkyokhoang/Man-in-the-Middle#19]
I try this code to remove the httponly flag but it does not work

```
responseHeaders.forEach(header => {
    if (header.name.toLowerCase() === 'set-cookie') {
        header.value = header.value.split(';')
            .filter(pair => pair.trim().toLowerCase() !== 'httponly')
            .join('; ');
    }
});
return responseHeaders;
```

From chrome documentation (https://developer.chrome.com/extensions/webRequest)

> Starting from Chrome 72, the following request headers are not provided and cannot be modified or removed without specifying 'extraHeaders' in opt_extraInfoSpec:
> 
> - Accept-Language
> - Accept-Encoding
> - Referer
> - Cookie
> 
> Starting from Chrome 72, the Set-Cookie response header is not provided and cannot be modified or removed without specifying 'extraHeaders' in opt_extraInfoSpec.

**Comment by dangkyokhoang** [comment]
I did read those from the doc when porting the extension to Chrome. However, I chose not to modify anything other than polyfilling the `browser` APIs. The Chrome version is aim at providing basic functionalities of the extension but not an equivalent to the Firefox version. This is because Chrome APIs is limited compared to Mozilla's.

A notable limitation is that it doesn't allow async event listeners which means that modifying requests using JavaScript is impossible and that the script above won't be working even if `extraHeaders` is specified. And it doesn't seem to be changed at all. The Chrome extension is therefore not likely going to improve.

Well, the Chrome extension hasn't been updated ever since its creation. I think it'll be updated soon, maybe next month :sweat: I'll do my best to make it more functional.

**Comment by dinh** [comment]
With this extension : https://github.com/pd4d10/tampery and the following script, I've managed to change the httponly flag

```
export default {
  lifecycle: 'onHeadersReceived',
  callback: ({ responseHeaders }) => {
    let hasHeader = false
    for (let i = 0; i < responseHeaders.length; i++) {
      if (
        responseHeaders[i].name.toLowerCase() === 'set-cookie'
      ) {
        responseHeaders[i].value = responseHeaders[i].value.split(';')
            .filter(pair => pair.trim().toLowerCase() !== 'httponly')
            .join('; ');
        hasHeader = true
      }
    }
    return { responseHeaders } // Return to change headers
  },
  filter: {
    urls: ['<all_urls>'], // Please change here, only include the sites you want
  },
  extraInfoSpec: [
    'responseHeaders', // Add `responseHeaders` to access response headers
    'blocking', // Add `blocking` here since we want to change response headers
    'extraHeaders'
  ],
}
```

**Comment by dangkyokhoang** [comment]
Changing headers using JavaScript is actually possible as the extension itself is in JavaScript. However, the extension (currently) use a sandbox frame to execute user-input JavaScript and it only works if async event handlers are supported. I'll see if it's possible to execute scripts without a sandbox. If I don't remember it wrong, Mozilla's policy doesn't allow such that behavior as it has some issue with extension's CSP. Hope there'll be a solution to this.

**Comment by dangkyokhoang** [comment]
Closing this as the Chrome version has been removed.
