### ISSUE TITLE
Response Rule messes up encoding

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#20]
Some pages get corrupted if you apply JavaScript replace rules to them.

Example:
`return responseBody.replace(/div/g, 'div');`
for the page [http://www.getchu.com/?gc=gc](http://www.getchu.com/?gc=gc)
will destroy it's encoding.

**Comment by dangkyokhoang** [comment]
This is because the native [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) API is used to encode responses and it only supports utf-8. The site above uses euc-jp, which is a legacy encoding and can't be encoded into utf-8 properly. Occasionally you'll find response rules break some other sites too.

Yes, it's an issue. But it might not be fixed.

**Comment by pintassilgo** [comment]
To solve this, create a `Header Rule`:
`Text headers` = `Content-Type: text/html; charset=UTF-8`
`Text type` = `Plaintext`
`Header type` = `Reponse Headers`.
