### ISSUE TITLE
Better matching system

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#3]
It's a pretty strange way to address everything with `*://*/*` insted of `*` or `.*` therefore it would be nice to streamline the matching methods for rules into a "Match rule(s)" field (full regex support and multiple match rules /regex/,/regex/), an "Exclude rule(s)" field (same functionality as Match rule(s)). And "Redirect field" (full regex support and script support) for "Match Success"-events and "Exclude triggered"-Events. Examples:

OriginalURL: `https://www.google.com`
MatchPattern: empthy -> applies to every request/response
ExcludePattern: empthy -> nothing will be excluded
RediredtPattern: empthy -> request will be blocked
ResultURL: -> nothing happens because every request will be blocked.

OriginalURL: `https://www.amazon.com/SanDisk-Ultra-Flair-Flash-Drive/dp/B015CH1GTO/ref=sr_1_1?ie=UTF8&qid=1538731454&sr=8-1&keywords=usb+16gb`
MatchPattern: `(https:\/\/www\.amazon\.com\/).*(dp\/[A-Za-Z0-9]+)\/.*`
ExcludePattern: `(https:\/\/www\.amazon\.com\/).*(dp\/[A-Za-Z0-9]{8})\/.*`
RediredtPattern: `$1$2` -> capture groups from "MatchPattern"
ResultURL: `https://www.amazon.com/dp/B015CH1GTO`

You also might take some inspiration from [this](https://addons.mozilla.org/en-US/firefox/addon/header-editor/) plugin. It doesn't allow css/js injections but it has a clearly better designed user interface: enable/disable rules, name rules, streamlined rule creation, rule tester, rule grouping.

**Comment by dangkyokhoang** [comment]
I'm currently working on those features 👍 
Match pattern is a browser-implemented method to match URLs. Using match pattern is perhaps more performant than using a custom method, but it's very limited. About the redirect URL, I do find that using a static URL for every requests has no meaning other than for reporting purposes.

**Comment by t2YU2m8l83** [comment]
As you can see in my amazon example it has significant purpose and is dynamic. It would remove all the tracking parameter and other useless informations from the link. But without regex in the redirect field it would definitely be pritty much pointless.

**Comment by dangkyokhoang** [comment]
I know.

**Comment by dangkyokhoang** [comment]
Version 3 released. Now you can name rules; use URL filters instead of match patterns to filter requests; redirect requests using regex.

**Comment by t2YU2m8l83** [comment]
The filter `/google\.com/` works perfectly fine with Content Scripts but nothing happens if I use it for Blocking Rules. Also I can leave the URL filter empthy for Content Scripts but Header Rules require `/.*/` to match everything.
On another note I noticed that an Enable/Disable switch for every rule would be a nice idea.

**Comment by dangkyokhoang** [comment]
- Request redirection doesn't work the way it should.
  Currently if a URL matches a RegExp filter, the extension will do something like this `destination = requestUrl.replace(regExp, redirectUrl);`. If the URL matches a string filter, then `destination = redirectUrl`. This isn't proper in some cases and might cause errors. Some detections are added (next version) but still some cases are not covered. :(
  The filter `/google\.com/` does work with Blocking Rules. If you don't set a redirect URL, you'll see every request to `google.com` blocked. If however you set a redirect URL, you have to set the redirect URL as below (so that`google.com` is replaced by `example.com`):
  ![image](https://user-images.githubusercontent.com/14311741/48436880-7355d500-e7b2-11e8-9078-5146f5e1b954.png)
  `http://example.com` as redirect URL just doen't work.
- URL filter for content script is currently optional.
  ![image](https://user-images.githubusercontent.com/14311741/48437735-c29d0500-e7b4-11e8-9c70-6c6e34e12eb4.png)
  However, it's going to become a required field in the next version. Having no filter doesn't seem to be a good practice I think. You probably don't want to block all requests or inject a script to every frames.
- The next version 3.1.0 is likely to be released tomorrow.

**Comment by dangkyokhoang** [comment]
Version 3.1.0 released, give it a try. Here's the summary of the changes:
````
New features:
- RESPONSE RULE - Ability to modify response body.
- Rules can now be enabled / disabled.
- Content scripts now have Origin URL filters.
- Options page opens in new tab.
- New Options page UI.

Improvements:
- Redirect URL now works perfectly.
- Content scripts run sooner.
- Content scripts require URL filters.

Fixed issues:
- Error inputing URL filters.
- Error setting headers containing ':'.
- ...
````

**Comment by t2YU2m8l83** [comment]
Blocking Rules doesn't work for me. Neither blocking nor redirect works with any kind of url filter. `/.*/`, `google.com`, `/google\.com/` , ...

**Comment by dangkyokhoang** [comment]
Can you post the screenshot of your blocking rules here as well as let me know the Firefox version, the extension version and the OS you're using?
Are blocking rules saved? Try reopening the options page and see if the rules are there.
Do your header rules and content scripts work?

**Comment by t2YU2m8l83** [comment]
Firefox Portable 63.0.1
Windows 7 Pro 64bit

Blocking Rules are saved.
Header Rules and Content Scripts work, haven't tested Response Rules yet.

The rule below should redirect you endless to google but nothing happens.

![x](https://user-images.githubusercontent.com/38610659/48578722-5c2df900-e912-11e8-9ff2-be237aeb98e1.jpg)

**Comment by dangkyokhoang** [comment]
The filter `/.*/` matches all requests. So if you leave the redirect URL unset, all requests are blocked. Open a new tab, try visting some website, `bing.com` for example, nothing really happens. Right? It's because the request to `bing.com` was blocked.

Now you set the redirect URL to `google.com`. Still nothing happens. Thats because `google.com` is not a valid URL and the browser just ignores it (see [https://en.wikipedia.org/wiki/URL](https://en.wikipedia.org/wiki/URL)). Instead you should write something like this: `https://www.google.com/`. It just works but an error occured - `The page isn’t redirecting properly`. Thats because the URL `https://www.google.com/` is also be redirected, to `https://www.google.com/` itself. So lets try something new:
- URL filters: `bing.com`
- Redirect URL: `https://www.google.com/`

It should work.

I'm sorry for this pic:
![Block request](https://user-images.githubusercontent.com/14311741/48436880-7355d500-e7b2-11e8-9078-5146f5e1b954.png)
As I stated before, `Request redirection doesn't work the way it should` in the previous version. Now it's corrected and `google.com` no longer works.

And your header rules work so blocking rules should work as they use the same method to filter requests.
![Blocking rule - Header rule - Request rule](https://user-images.githubusercontent.com/14311741/48581515-a2a44780-e954-11e8-9528-2c656a7b8789.png)

**Comment by t2YU2m8l83** [comment]
I've done some testing with different firefox versions and Operation Systems. The result was that only my extremely customized browser ignores the top most rule in the Blocking Rules section. I don't know which about:config option this behaviour triggers and as long as I can't find a good way to see only the changed values I'm not gonna even try to find it out. Therefore creating an empthy rule for the top most entry is sufficind to get everything working again.

Bugs/Problems/Suggestions still remaining:
Necessary:
-Regex Negative Lookbehinds `(?<!)` don't work
-An "Exclude Pattern" field would be great and make the Negative Lookbehind problem obsolet. It's pretty usefull for conditional rules `if url == google.com && !url.contains("q=") do redirect("google.com?q=test")`

Nice to have:
-A better function to edit headers:
```
requestHeaders.AddOrOverride(Name, Value){
var existingHeader = requestHeaders.find(({name}) => (
name.toLowerCase() === Name.toLowerCase()
));

if (existingHeader === undefined){
requestHeaders.push({name: Name,value: Value});
}
else{
existingHeader.value = Value;
}
}
```
-The Enable/Disable button could be placed at the end of every collapsed row for easy access.
-Make rules groupable
-Make the rule order changeable
-Tab-button support for aligning codeblocks/styleblocks in text fields
-Markup for css/js keywords and autocomplete for css-rules/js-functions

Unimportant:
- First Blocking Rule gets ignored (only in my browser)

**Comment by dangkyokhoang** [comment]
I've open new issues in regard to your comment.
Since the current issue is about the new matching system, which is implemented in the current extension version, I'd like to close this issue here. `Exclude Pattern` is to be discussed on another issue - https://github.com/dangkyokhoang/Man-in-the-Middle/issues/5. Thank you so much for your valued reports and suggestions to make the extension better.
