### ISSUE TITLE
Need simple example how to use this repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [dangkyokhoang/Man-in-the-Middle#35]
Hello:
I need this add-on to forward some https requests.
However, it seems not easy to use this add-on.
For example, if I want simply to show the URL that I am interested in.
For example: 
If I visit MDN Web site: 
https://developer.mozilla.org/
I want to show all the URLs begin with this domain.
I just want to simply use console.log(url) to show which URLs are being downloaded (HTTP GET).
Please show me the code, rules how to simply show the URLs beging with https://developer.mozilla.org/
Thanks,

**Comment by dangkyokhoang** [comment]
This is an example of Blocking Rule that logs matched requests to a local server.
![Man in the Middle](https://user-images.githubusercontent.com/14311741/112030226-9fe13f00-8b6c-11eb-90d4-7774e52dc8bf.png)
And here's the result.
![Man in the Middle](https://user-images.githubusercontent.com/14311741/112031561-116dbd00-8b6e-11eb-8285-ac4b9e9dfa9a.png)

You can't use `console.log` because the JavaScript is executed inside a restricted sandbox (https://github.com/dangkyokhoang/man-in-the-middle#restricted-javascript)

**Comment by zydjohnHotmail** [comment]
Thanks I will do some testing to know this.  But it seems your repo can solve my issue.
